{{- if and (eq .Values.history.backend "oracle") .Values.history.oracle.dsn .Values.history.oracle.user .Values.history.oracle.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smg.fullname" . }}-secrets
  labels:
    {{- include "smg.labels" . | nindent 4 }}
type: Opaque
stringData:
  oracle-dsn: {{ .Values.history.oracle.dsn | quote }}
  oracle-user: {{ .Values.history.oracle.user | quote }}
  oracle-password: {{ .Values.history.oracle.password | quote }}
{{- end }}
